# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cd2bd84a6421296120f166f7c5fe5bf0d3f4c4afc893eefed0d66791fbf09e9fcbd9674b43fd8735971154c9a899c0e34a14d9283ce721ae302c95a1f035973c

test:
  secret_key_base: c1072e8148b740389f11f91e20e721cf1f5fda19f8a3ed0477338f2c1cb3da6359f902499f4140146be6e9949752e40f55e17c79f49dab9eb8d361f1be7633b8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
